apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::018986061723:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11KGY9YAXH805
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::018986061723:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T13:18:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3834"
  uid: 1cf7b744-a8bf-4f60-852d-ce19bb1d88c9
